apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: facenet-api
  namespaceSelector:
    matchNames:
      - mlops
  endpoints:
    - port: http
      path: /metrics
      interval: 15s