FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    rm -rf /root/.cache/pip

COPY . /app
# Expose port
EXPOSE 8080

CMD ["python", "data_preprocess.py"]