apiVersion: v1
kind: Service
metadata:
  name: facenet-api-service
  namespace: mlops
  labels:
    app: facenet-api
spec:
  selector:
    app: facenet-api
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 8001