apiVersion: batch/v1
kind: Job
metadata:
  name: dag-uploader
  namespace: airflow
spec:
  ttlSecondsAfterFinished: 60 
  template:
    metadata:
      name: dag-uploader
    spec:
      nodeSelector:
        #kubernetes.io/hostname: gke-facenet-airflow-gpu-pool-d96bb835-bm9f
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      restartPolicy: Never
      containers:
        - name: uploader
          image: busybox
          command: ['sh', '-c', 'sleep 3600']
          volumeMounts:
            - mountPath: /mnt/dags
              name: dags-volume
      volumes:
        - name: dags-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc