executor: LocalExecutor

images:
  airflow:
    repository: apache/airflow
    tag: 2.7.2-python3.9
    pullPolicy: IfNotPresent
    
airflow:
  installRequirements: true
  extraPipPackages:
    - apache-airflow-providers-docker
    - docker
    - apache-airflow-providers-cncf-kubernetes
    - apache-airflow-providers-fab 
  config:
    AIRFLOW__CORE__AUTH_MANAGER: airflow.auth.managers.fab.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
    AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
    AIRFLOW__SMTP__SMTP_USER:  ******@gmail.com
    AIRFLOW__SMTP__SMTP_SSL: "false"
    AIRFLOW__SMTP__SMTP_PASSWORD: ******
    AIRFLOW__SMTP__SMTP_STARTTLS: "true"
    AIRFLOW__SMTP__SMTP_PORT: 587
    AIRFLOW__SMTP__SMTP_MAIL_FROM: ******@gmail.com
  users:
    - username: admin
      password: admin
      role: Admin
      email: egatch2017@gmail.com
  extraEnv:
    - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS
      value: "True"

webserver:
  service:
    type: LoadBalancer  
    annotations: {}

scheduler:
  replicas: 1

triggerer:
  replicas: 1

dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags-pvc  
    subPath: ""  
  gitSync:
    enabled: false  

logs:
  persistence:
    enabled: true
    existingClaim: airflow-logs-pvc 

postgresql:
  enabled: true  

redis:
  enabled: false  